apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: fast-api
  rules:
    - host: 192-168-1-138.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fast-api
                port:
                  number: 80
